src/actionCreators.ts
There's a bug that after a failed sign-out due to an authorization error, it retries to perform the sign out until it succeeds, or the rate limiter hits. This can happen when the user session has expired and you try to sign-out.
This PR fixes the issue.
1. Set your CL node's `SESSION_TIMEOUT` env var to `1s`
2. Log into the UI
3. Wait a second
4. Try to sign out
5. Check web console and CL node console
6. No error should be displayed
7. You should be redirected to the sign-in page
=> Fix `infinite` sign-out loop on auth token expiration sign-out request

.changeset/green-otters-pull.md, src/screens/JobRun/JobRunView.tsx, src/screens/JobRun/TaskRunItem.test.tsx, src/screens/JobRun/TaskRunItem.tsx
Fixes task run status display for `ethtx` type.
1. Run the Operator UI with a CL node running
2. Setup a simple Job to request ethereum prices
3. Trigger the job run from the corresponding smart contract
4. Verify that in the UI, the `ethtx` task run is pending until it is confirmed
5. Or you can just follow the official guide: https://docs.chain.link/docs/fulfilling-requests/
Here's a screenshot displaying how it should look like: 
=> Fixes task run status display for `ethtx` type

src/screens/Configuration/ConfigurationV2Card/ConfigurationV2Card.tsx
This PR updates the `ConfgurationV2Card` to display raw TOML as a code block, rather than splitting in to table rows:
Before:
After:
=> ConfigurationV2Card: swap out toml table for code block

src/pages/Chains/NodeRow.tsx, src/pages/Chains/NodesList.tsx, src/screens/Chains/ChainRow.test.tsx, src/screens/Chains/ChainRow.tsx, src/screens/Chains/ChainsView.test.tsx, src/screens/Chains/ChainsView.tsx, src/screens/Node/NodeCard.test.tsx, src/screens/Node/NodeCard.tsx, src/screens/Node/NodeView.test.tsx, src/screens/Nodes/NodeRow.test.tsx, src/screens/Nodes/NodeRow.tsx, src/screens/Nodes/NodesView.test.tsx, src/screens/Nodes/NodesView.tsx
With new config, Chains and Nodes no longer have integer database IDs or 'Created' timestamps. This change removes them from view, substituting `Name` for a unique Node identifier.
=> drop ID and Created from Chains and Nodes

src/screens/Job/JobView.tsx, src/screens/Job/generateJobDefinition.test.ts, src/screens/Job/generateJobDefinition.ts
ID is internal to the DB and shouldn't be part of the displayed job spec. It was mistakenly added in https://github.com/smartcontractkit/chainlink/pull/5882
3. Go to jobs -> new job -> create a job of type bootstrap and save it. Then load its definition and verify there is no "id" field listed there.
=> Remove ID attribute from bootstrap job spec

src/screens/Job/JobView.tsx, src/screens/Job/generateJobDefinition.test.ts, src/screens/Job/generateJobDefinition.ts
Add [`gasLanePrice`](https://github.com/smartcontractkit/chainlink/blob/develop/core/web/schema/type/spec.graphql#L111) to the `VRFSpec` query. This is so that `gasLanePrice` is correctly rendered in the job details page for VRF v2 jobs.
1. Spin up a CL node.
2. Create a VRF job with `gasLanePrice` correctly specified (e.g `"200 gwei"`)
3. Verify that `gasLanePrice = "200 gwei"` is correctly rendered in the VRF job details UI.
=> screens/Job: add gasLanePrice to VRFSpec query

.changeset/sweet-turkeys-mate.md, src/pages/Header.tsx
Adds the Feeds Manager navigation link to display in the Navigation Drawer when on mobile view
Ensure Feeds Manager is enabled via your env vars
1. Login to the Operator UI
2. View a page in mobile view
3. Open the navigation drawer
4. You should see the Feeds Manager link which will navigate you to the feeds manager page
5. 
https://user-images.githubusercontent.com/61834/202719365-72a53fc9-9421-404c-a01f-5cb966ce8175.mov
=> Display the Feeds Manager navigation link in mobile view drawer

src/screens/Configuration/ConfigurationCard/ConfigurationCard.tsx, src/screens/Configuration/ConfigurationV2Card/ConfigurationV2Card.tsx, src/screens/Configuration/ConfigurationView.test.tsx
This change updates the config screen to be more user friendly and dynamic with legacy vs. TOML.
1. Removed the `(legacy)` suffix from ENV, let the error speak for itself when using TOML:
2. When legacy config is in use, show only the dumped TOML, with an alternative title:
=> dynamic config for legacy vs. TOML

.changeset/silly-jokes-lay.md, src/screens/Dashboard/AccountBalanceCard.tsx, src/screens/KeyManagement/EVMAccountsCard.test.tsx, src/screens/KeyManagement/EVMAccountsCard.tsx
Changed "ETH balance" with "Native token balance" to be more user-friendly/less confusing on different chains
Task link: https://smartcontract-it.atlassian.net/browse/BCF-1674
Github issue: https://github.com/smartcontractkit/chainlink/issues/6784
=> Changed "ETH balance" with "Native token balance" 

.changeset/shiny-lobsters-check.md, src/screens/FeedsManager/JobProposalsCard.test.tsx, src/screens/FeedsManager/JobProposalsCard.tsx, src/screens/JobProposal/SpecsView.test.tsx, src/screens/JobProposal/SpecsView.tsx, support/factories/gql/fetchFeedsManagersWithProposals.ts
This PR adds a revoked tab in the Job Proposals view in Feeds Manager that displays all the revoked job proposals. Only pending proposals can be revoked, and while revoked, cannot be approved. FMS can repropose a new spec and it will become a new pending spec for the same proposal, also updating the status of the proposal from revoked to pending.
=> add revoked jobs tab to feeds manager

.changeset/mean-wasps-cover.md, src/components/Form/ChainConfigurationForm.test.tsx, src/components/Form/ChainConfigurationForm.tsx, src/hooks/queries/useFeedsManagersWithProposalsQuery.ts, src/screens/FeedsManager/EditSupportedChainDialog.tsx, src/screens/FeedsManager/NewSupportedChainDialog.tsx, src/screens/FeedsManager/SupportedChainsCard.tsx
=> Add OCR2 plugins selection for FMS

.changeset/purple-feet-nail.md, src/screens/Job/JobView.tsx, src/screens/Job/generateJobDefinition.ts
adding a new job definition for block header feeder
related core PR: https://github.com/smartcontractkit/chainlink/pull/8790
3. ...etc
- [DONE] This PR has an accompanying changeset if needed.
=> Vrf 415 31732 vrf automatic bhs backwards mode

.changeset/tender-trees-cover.md, @types/core/store/models.d.ts, src/screens/Node/NodeView.tsx, src/screens/Nodes/NodeRow.tsx, src/screens/Nodes/NodesScreen.test.tsx, src/screens/Nodes/NodesView.test.tsx, src/screens/Nodes/NodesView.tsx, support/factories/gql/fetchNodes.ts
Add node order column in the `Nodes` screen
GQL schema changes PR: https://github.com/smartcontractkit/chainlink/pull/9554
=> Add node order

.changeset/tame-penguins-shake.md, src/screens/Configuration/ConfigurationV2Card/ConfigurationV2Card.tsx
Adding announcement for deprecation of simple passwords in config page
3.  Login
4. Navigate to config page and view notification
- [X ] This PR has an accompanying changeset if needed.
=> chore/simple-passwords-announcement: adding announcement for deprecation of simple passwords in config page

.changeset/sharp-rice-melt.md, src/components/Form/ChainConfigurationForm.test.tsx, src/components/Form/ChainConfigurationForm.tsx, src/hooks/queries/useFeedsManagersWithProposalsQuery.ts, src/screens/FeedsManager/EditSupportedChainDialog.tsx, src/screens/FeedsManager/NewSupportedChainDialog.tsx, src/screens/FeedsManager/SupportedChainsCard.tsx
Add support for setting operator forwarder address for OCR2 jobs managed by FMS
3. ...etc
=> add feeds manager operator forwarder support for ocr2

.changeset/shy-moose-walk.md, src/screens/Configuration/ConfigurationV2Card/ConfigurationV2Card.tsx
`<description>`
3. ...etc
- [x ] This PR has an accompanying changeset if needed.
=> BCF-2591-allow-simple-passwords: reverting notification

src/screens/Configuration/ConfigurationV2Card/ConfigurationV2Card.tsx, src/screens/Job/JobView.tsx, src/screens/Job/TabDefinition.tsx, src/screens/Job/generateJobDefinition.test.ts, src/screens/Job/generateJobDefinition.ts, support/factories/gql/fetchJob.ts
Update job gql to match core changes in this PR:
https://github.com/smartcontractkit/chainlink/pull/11119
=> BCF-2672 Update job gql to reflect core node changes

.changeset/gold-poems-relax.md, src/screens/Job/JobView.tsx, src/screens/Job/generateJobDefinition.test.ts, src/screens/Job/generateJobDefinition.ts
Remove the P2P V1 field `p2pBootstrapPeers`. 
Supports:
- https://github.com/smartcontractkit/chainlink/pull/10872
=> remove p2p v1 field p2pBootstrapPeers

scripts/release.mts
Modifying the `release.mts` script to exclude previous releases changelog entries.
1. Add `--draft` to `scripts/release.mts` to ensure you don't create a github release
```
await $`gh release create --draft ...`
```
2.  While in `scripts` directory - `yarn release`
<details><summary>Changelog Diff From Testing</summary>
<p>
```
diff --git a/CHANGELOG.md b/CHANGELOG.md
index 319620a..24c18ba 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -1,32 +1,51 @@
-## 0.7.0
+## 0.8.0-0953c48
-- d5517c9: Swap out compiler for testing and building for swc
+- 53c5f87: rename fromAddress to fromAddresses in blockhashStoreSpec
+- b286a55: Remove the `maxGasPriceGWei` field from VRF job details page.
+- 374e9b4: Displays feed ID on OCR2 JobSpec
+- 3c7a06f: Add ability to show TOML config
+
+  On the …
```
=> fix: changelog release entries

.github/workflows/cd.yml
Updating to use in-house [`changesets-signed-commits`](https://github.com/smartcontractkit/.github/releases/tag/changesets-signed-commits%401.0.1) rather than the official `changesets/action` github action which doesn't support commit signing.
N/A - this change only effects CI/CD workflows
---
https://smartcontract-it.atlassian.net/browse/RE-2179
=> feat: use changesets-signed-commits

.changeset/purple-humans-explain.md, .github/workflows/chainlink-ci.yml
This adds a new `tag` input to chainlink-ci workflow to fix a bug that only checks out the latest commit of this repo when being trigger by chainlink.
3. ...etc
=> add tag input to chainlink-ci workflow

.changeset/brown-rivers-accept.md, src/screens/Job/JobView.tsx, src/screens/Job/generateJobDefinition.test.ts, src/screens/Job/generateJobDefinition.ts
Add support for workflow spec job types.
3. ...etc
=> [KS-135] Add workflow spec job type

.github/workflows/cd.yml, .github/workflows/chainlink-ci.yml, .github/workflows/ci.yml
Updating Github Action references in all workflows.
Github Actions node16 deprecation. See [blog post (github.blog)](https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/)
> Node16 has been out of support since [September 2023](https://github.com/nodejs/Release/#end-of-life-releases). As a result we have started the deprecation process of Node16 for GitHub Actions. We plan to migrate all actions to run on Node20 by Spring 2024.
> Following on from our [warning in workflows using Node16](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/) we will start enforcing the use of Node20 rather than Node16 on the 13th of May.
RE-2531
Outdated Dependency Paths:
```
Workflow:CI ---> Job:eslint …
```
=> chore: github action version bumps

.changeset/dirty-planes-promise.md, src/components/Form/ChainConfigurationForm.tsx
Remove the chainType filter for feeds manager until we can return chain type in the chain resolver
=> remove chaintype filter on bundleid

.changeset/modern-balloons-sneeze.md, src/Private.tsx, src/components/Form/FeedsManagerForm.tsx, src/pages/Header.tsx, src/screens/Bridges/BridgesScreen.test.tsx, src/screens/EditFeedsManager/EditFeedsManagerScreen.test.tsx, src/screens/EditFeedsManager/EditFeedsManagerScreen.tsx, src/screens/EditFeedsManager/EditFeedsManagerView.test.tsx, src/screens/EditFeedsManager/EditFeedsManagerView.tsx, src/screens/FeedsManager/FeedsManagerCard.test.tsx, src/screens/FeedsManager/FeedsManagerCard.tsx, src/screens/FeedsManager/FeedsManagerScreen.test.tsx, src/screens/FeedsManager/FeedsManagerScreen.tsx, src/screens/FeedsManager/FeedsManagerView.test.tsx, src/screens/FeedsManager/FeedsManagerView.tsx, src/screens/JobProposal/JobProposalScreen.test.tsx, src/screens/JobProposal/JobProposalScreen.tsx, src/screens/NewFeedsManager/NewFeedsManagerScreen.test.tsx, src/screens/NewFeedsManager/NewFeedsManagerScreen.tsx, src/screens/NewFeedsManager/NewFeedsManagerView.test.tsx, src/screens/NewFeedsManager/NewFeedsManagerView.tsx
Feeds Manager is an outdated term, now that we are rolling out [Job Distributor](https://github.com/smartcontractkit/job-distributor), we want to start adopting the new name.
We are only performing the rename on a superficial level which is on the UI, the rest including the backend remains untouched to keep things simple.
This is in preparation of the incoming changes to support registering more than job distributor per node.
Note: urls are also renamed eg `localhost/feeds_manager` -> `localhost/job_distributors`
JIRA: https://smartcontract-it.atlassian.net/browse/OPCORE-891
=> [OPCORE-891] fix: Rename Feeds Manager -> Job Distributors 

src/hooks/queries/useFeedsManagersQuery.ts, src/screens/FeedsManager/ConnectionStatus.tsx, src/screens/FeedsManager/FeedsManagerCard.tsx, src/screens/JobDistributors/JobDistributorsRow.tsx, src/screens/JobDistributors/JobDistributorsScreen.test.tsx, src/screens/JobDistributors/JobDistributorsScreen.tsx, src/screens/JobDistributors/JobDistributorsView.test.tsx, src/screens/JobDistributors/JobDistributorsView.tsx, support/factories/gql/fetchFeedsManagers.ts
Since we now plan to support more than 1 feeds manager/job distributor, we want to have a home page where it shows a list of registered feeds managers. I also had to refactor the `ConnectionStatus` component out so i can reuse it in my new page.
Note: in order to keep my upcoming PRs small, this PR is purely for adding the react components for the brand new home page. **They are currently not used yet. They will be used in the upcoming PR.**
JIRA: https://smartcontract-it.atlassian.net/browse/OPCORE-858
No Changeset needed as this is just adding a few files, no integration yet. When i integrate the new page, i will add the changeset.
New home page for job distributors
=> [OPCORE-858]: feat: new distributor home page (NOT INTEGRATED)

.changeset/chilly-garlics-remember.md, src/screens/NewFeedsManager/NewFeedsManagerScreen.test.tsx, src/screens/NewFeedsManager/NewFeedsManagerScreen.tsx, src/screens/NewFeedsManager/NewFeedsManagerView.test.tsx, src/screens/NewFeedsManager/NewFeedsManagerView.tsx
The current behaviour is when we navigate to `job_distributors/new` page, if there is at least 1 registered job distributor, it will redirect to `/job_distributors`. We want to stop redirecting to `/job_distributors` in this scenario since we now want to support adding more than 1 manager.
JIRA: https://smartcontract-it.atlassian.net/browse/OPCORE-858
=> [OPCORE-858]: fix(NewFeedsManagerScreen): no longer redirect

.changeset/cyan-kids-boil.md, src/components/Form/ChainConfigurationForm.test.tsx, src/components/Form/ChainConfigurationForm.tsx, src/screens/FeedsManager/SupportedChainsCard.tsx
Add a new field for peerID in the chain config form when it is running as bootstrap node for OCR2.
When `Is this node running as a bootstrap peer?` is selected, peerId is now available as a field.
Context: https://chainlink-core.slack.com/archives/C0577D7CNLV/p1726068910380289?thread_ts=1726068645.524679&cid=C0577D7CNLV
JIRA: https://smartcontract-it.atlassian.net/browse/OPCORE-948
=> [OPCORE-948]: fix(chain): peerId is available for bootstrap

.changeset/serious-turtles-fold.md, src/components/Form/ChainConfigurationForm.test.tsx, src/components/Form/ChainConfigurationForm.tsx, src/components/Form/ChainTypes.ts, src/hooks/queries/useAptosAccountsQuery.test.tsx, src/hooks/queries/useAptosAccountsQuery.ts, src/hooks/queries/useChainsQuery.ts, src/screens/FeedsManager/EditSupportedChainDialog.tsx, src/screens/FeedsManager/NewSupportedChainDialog.tsx, support/factories/gql/fetchChains.ts
Allow APTOS to be selected in the chainconfig modal instead of just EVM.
The goal is being able to support APTOS in core node.
JIRA: https://smartcontract-it.atlassian.net/browse/DPA-1155
Pending [this PR](https://github.com/smartcontractkit/chainlink/pull/14718) to be merged for the new `network` field.
=> [DPA-1155]: feat(chainconfig): support aptos

.changeset/real-zoos-jump.md, src/components/Form/ChainConfigurationForm.test.tsx, src/components/Form/ChainConfigurationForm.tsx
Making admin address field on the chain config popup optional instead of required, now that we introduced APTOS support on the popup, APTOS does not require admin address.
No changes to the backend required as it happily accepts empty string as a valid value.
I did a quick investigation on what happens if admin address is empty when passed into CLO & JD, looks like the field just get passed along, so if we dont provide a value, nothing happens. It jus shows empty value when user looks it up from the API.
JIRA: https://smartcontract-it.atlassian.net/browse/DPA-1160
3. ...etc
If this PR creates changes to the operator-ui itself, rather than tests, pipeline changes, etc. Then please create a changeset so that a new release is created, and the changelog …
=> [DPA-1160]: fix(chainconfig): make adminAddr optional

.changeset/eight-parents-leave.md, src/hooks/queries/useFeedsManagerWithProposalsQuery.ts, src/hooks/queries/useFeedsManagersQuery.ts, src/screens/FeedsManager/FeedsManagerCard.test.tsx, src/screens/FeedsManager/FeedsManagerCard.tsx, src/screens/FeedsManager/FeedsManagerScreen.test.tsx, src/screens/FeedsManager/FeedsManagerScreen.tsx, src/screens/FeedsManager/FeedsManagerView.test.tsx, src/screens/FeedsManager/FeedsManagerView.tsx, src/screens/FeedsManager/StatusIndicator.tsx, src/screens/JobDistributors/JobDistributorsRow.tsx, src/screens/JobDistributors/JobDistributorsView.test.tsx, src/screens/JobDistributors/JobDistributorsView.tsx, support/factories/gql/fetchFeedsManagers.ts, support/factories/gql/fetchFeedsManagersWithProposals.ts
https://smartcontract-it.atlassian.net/browse/DPA-1067
Update UI with Enable/Disable JD mutations.
=> feat: add enable and disable feed manager queries

src/screens/Job/JobView.tsx, src/screens/Job/generateJobDefinition.test.ts, src/screens/Job/generateJobDefinition.ts, yarn.lock
Frontend changes corresponding to the backend change here: https://github.com/smartcontractkit/chainlink/pull/15044. We want to make sure that the new Stream jobs are correctly displayed on the jobs page.
=> Add StreamSpec

.changeset/strong-ads-jump.md, src/components/Form/ChainConfigurationForm.test.tsx, src/components/Form/ChainConfigurationForm.tsx, src/screens/FeedsManager/EditSupportedChainDialog.tsx
Allow user to manually input ChainId and Account Address when there are no selections available.
When creating a chain config in operator ui, if the core node is not configured with APTOS RPC, user wont be able to create a chain config because there are nothing to select from in the ChainId and Account Address field in the chain config popup.
This is a new scenario for Keystone where a chain config needs to be created even if there are no existing connection to an RPC.
JIRA: https://smartcontract-it.atlassian.net/browse/DPA-1306
=> [DPA-1306]: fix(chain-config): allow manual input

.changeset/nervous-cups-invite.md, src/components/Form/ChainConfigurationForm.test.tsx, src/components/Form/ChainConfigurationForm.tsx
For the ocr2 keybundle id select box, it lists all the keys based on the ID and it's hard to tell which one we want. Adding the key type (aptos, evm etc) to the values in the selectbox, something like "0xaaabbbccc (aptos)" so it can be easily identified now that we support more than EVM chain.
JIRA: https://smartcontract-it.atlassian.net/browse/DPA-1321
=> [DPA-1321]: fix(chainconfig): attach label to key bundle id

.changeset/eighty-apricots-rest.md, src/apollo.ts, src/components/Form/ChainConfigurationForm.test.tsx, src/hooks/queries/useEVMAccountsQuery.ts, src/screens/Dashboard/AccountBalanceCard.tsx, src/screens/Node/NodeView.tsx, src/screens/Nodes/NodesView.tsx, src/screens/Transaction/TransactionView.tsx, src/screens/Transactions/TransactionsView.tsx, support/factories/gql/fetchAccountBalances.ts, support/factories/gql/fetchETHKeys.ts, support/factories/gql/fetchEthTransaction.ts, support/factories/gql/fetchEthTransactions.ts, support/factories/gql/fetchNode.ts, support/factories/gql/fetchNodes.ts
If the chains query returns different chain with same id eg
```
[
{
"id": "1",
"enabled": true,
"network": "aptos",
"__typename": "Chain"
},
{
"id": "1",
"enabled": true,
"network": "evm",
"__typename": "Chain"
}
]
```
The default apollo client behaviour is to assume ID is always unique, but it is not the case here so things start to become confused like in the screen shot where both “1” show up for APTOS even though the UI correctly filters it.
The fix is to tell apollo client how to handle the uniqueness of the chain object.
JIRA: https://smartcontract-it.atlassian.net/browse/DPA-1384
=> [DPA-1384]: fix(chain): override apollo ID matching for chain

.changeset/brown-horses-give.md, src/components/Form/ChainConfigurationForm.test.tsx, src/components/Form/ChainConfigurationForm.tsx, src/components/Form/ChainTypes.ts, src/hooks/queries/useNonEvmAccountsQuery.test.tsx, src/hooks/queries/useNonEvmAccountsQuery.ts
Able to create TRON chain config from the job distributor page.
Dependent on [this PR](https://github.com/smartcontractkit/chainlink/pull/14783) to be merged
JIRA: https://smartcontract-it.atlassian.net/browse/DPA-1333
=> [DPA-1333]: feat: create tron chain config support

.changeset/hot-mails-rhyme.md, src/screens/FeedsManager/EditSupportedChainDialog.tsx, src/screens/FeedsManager/NewSupportedChainDialog.tsx
config dialog
Increases limit for the number of chains.
3. `start chainlink node with more than 50 chains`
4. `Login to the UI and add one Job Distributor`
5. `Try to add new supported chain in JD and make sure that all chains are listed in drop down list`
=> fix: use large limit to fetch all chains in FMS chain

.changeset/flat-toys-roll.md, src/screens/JobProposal/SpecsView.test.tsx, src/screens/JobProposal/SpecsView.tsx
Display the "Approve" button on the latest two versions of a job spec in the "job proposal details" page that have the "cancelled" status. This allows users to approve older versions of a job spec.
This PR must be deployed along with PR # from the core repo.
[DX-534](https://smartcontract-it.atlassian.net/browse/DX-534)
3. Select a job proposal that has multiple versions
4. Check that all versions in the "cancelled" state have an `Approve` button
5. Approve an order version of a job spec
6. If there was another job previously in the "approved", an error message should be displayed
7. If needed, cancel the version that is currently approved (likely the newest one)
8. Try to approve an older job spec.
9. If no other version was in the "approved" …
=> feat: allow approval of previous versions of job specs
